# Markdownlint Configuration for GoingEnv
# See: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Disable specific rules that are too strict for our documentation
MD013: false  # Line length - allow longer lines for code examples and links
MD022: false  # Blanks around headings - allow flexible heading spacing
MD024: false  # Duplicate headings - allow same headings in different sections  
MD031: false  # Blanks around fences - allow flexible code block spacing
MD032: false  # Blanks around lists - allow flexible list spacing
MD033: false  # Inline HTML - allow HTML for badges and formatting
MD034: false  # Bare URLs - allow bare URLs in documentation
MD036: false  # Emphasis as heading - allow emphasis for sub-points
MD040: false  # Fenced code language - allow code blocks without language
MD041: false  # First line in file should be a top level header - allow for badges
MD047: false  # Single trailing newline - allow flexible file endings

# Configure specific rules
MD003:
  style: "atx"  # Use # style headers

MD004:
  style: "dash"  # Use - for unordered lists

MD007:
  indent: 2  # Unordered list indentation (2 spaces)

MD010:
  spaces_per_tab: 2  # Tab width

MD012:
  maximum: 2  # Maximum consecutive blank lines

MD025:
  front_matter_title: ""  # Allow multiple H1 headers if front matter has title

MD026:
  punctuation: ".,;:!?"  # Trailing punctuation in headers

MD029:
  style: "ordered"  # Ordered list item prefix (1. 2. 3.)

MD030:
  ul_single: 1  # Spaces after list markers (unordered, single-line)
  ol_single: 1  # Spaces after list markers (ordered, single-line)
  ul_multi: 1   # Spaces after list markers (unordered, multi-line)
  ol_multi: 1   # Spaces after list markers (ordered, multi-line)

MD035:
  style: "---"  # Horizontal rule style

MD046:
  style: "fenced"  # Code block style (use ``` instead of indented)

MD048:
  style: "backtick"  # Code fence style (use ``` instead of ~~~)